code_area/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('judge.urls')),
]

judge/urls.py
from django.urls import path

from . import views

app_name='judge'

urlpatterns = [
    path('signin/',views.signin,name='signin_url'),
    path('add_user/',views.add_user,name='add_user_url'),
    path('login_page/',views.login_page,name='login_page_url'),
    path("",views.home,name='home_url'),
    path("<int:id>",views.description,name='description_url'),
    path('logout/',views.logout_user,name='logout_url'),
    path("<int:id>/verdict",views.verdict,name='verdict_url')
]

judge/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class problems(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)

    def __str__(self):
        return str(self.name)

class testcase(models.Model):
    input = models.TextField()
    output = models.TextField()
    prob = models.ForeignKey(problems,on_delete=models.CASCADE)

    def __str__(self):
        return str( "TC:" + str(self.id) + " for " +  str(self.prob))

judge/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import problems,testcase
import docker,subprocess
from time import time
# Create your views here.
def signin(request):
    return render(request, 'signin.html')

def add_user(request):
    if request.method == "POST":
        username,emailid,pass1,pass2 = request.POST['username'],request.POST['email'],request.POST['pass1'],request.POST['pass2']
        if pass1==pass2:
            new_user = User.objects.create(username=username,email=emailid,password=pass1)
            new_user.save()
        return redirect('judge:login_page_url')
    else:
        return render(request,'signin.html')
    
def login_page(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        u = authenticate(request,username=username,password=password)
        if u is not None:
            login(request,u)
            print('logged in')
            return HttpResponse('successfully logged in')
        else:
            context = {'msg' : 'username or password is not correct'}
            return render(request,'login.html',context)
    return render(request,'login.html')
        

@login_required(login_url='login_page/')
def home(request):
    problem_list = problems.objects.all()
    user = request.user
    context = {'list' : problem_list,'user':user}
    return render(request,'home.html',context)

@login_required(login_url='../login_page/')
def description(request,id):
    problem = problems.objects.get(id = id)
    context={'problem':problem}
    return render(request,'description.html',context)

@login_required(login_url='../../login_page/')
def verdict(request,id):
    if request.method=='POST':
        docker_client = docker.from_env()
        Running = "running"
        problem = problems.objects.get(id=id)
        tc = testcase.objects.get(prob_id=id)
        print(tc)
        #replacing \r\n by \n in original output to compare it with the usercode output
        tc.output = tc.output.replace('\r\n','\n').strip() 

        verdict = "Wrong Answer" 
        res = ""
        run_time = 0

        user_code,language = request.POST['code'],request.POST['language']

        filename = 'user_code'
        file = filename + '.py'
        filepath = file

        cont_name = 'python_compiler'
        extension = '.py'
        docker_img = 'python'
        exe = f"python {filename}.py"
        clean = f"{filename} {filename}.c"
        compile = 'python'

        code = open(filepath,"w")
        code.write(user_code)
        print('user code : ',user_code)
        code.close()

        try:
            container = docker_client.containers.get(cont_name)
            container_state = container.attrs['State']
            container_is_running = (container_state['Status'] == Running)
            if not container_is_running:
                subprocess.run(f"docker start {cont_name}",shell=True)
        except docker.errors.NotFound:
            subprocess.run(f"docker run -dt --name {cont_name} {docker_img}",shell=True)

        c=subprocess.run(f"docker cp {filepath} {cont_name}:/{file}",shell=True)
        print(c)
        # compiling the code
        cmp = subprocess.run(f"docker exec {cont_name} {compile}", capture_output=True, shell=True)
        print(cmp)
        if cmp.returncode != 0:
            verdict = "Compilation Error"
            subprocess.run(f"docker exec {cont_name} rm {file}",shell=True)

        else:
            # running the code on given input and taking the output in a variable in bytes
            start = time()
            try:
                c = f'docker exec {cont_name} sh -c "echo {tc.input}| {exe}" '

                res = subprocess.run(c,capture_output=True, timeout=2, shell=True)
                print(c)
                run_time = time()-start
                subprocess.run(f"docker exec {cont_name} rm {clean}",shell=True)
            except subprocess.TimeoutExpired:
                run_time = time()-start
                verdict = "Time Limit Exceeded"
                subprocess.run(f"docker container kill {cont_name}", shell=True)
                subprocess.run(f"docker start {cont_name}",shell=True)
                subprocess.run(f"docker exec {cont_name} rm {clean}",shell=True)

            print(res.stdout,res.stderr,res.returncode,sep='\n')
            if verdict != "Time Limit Exceeded" and res.returncode != 0:
                verdict = "Runtime Error"

        user_stderr = ""
        user_stdout = ""
        if verdict == "Compilation Error":
            user_stderr = cmp.stderr.decode('utf-8')
        
        elif verdict == "Wrong Answer":
            user_stdout = res.stdout.decode('utf-8')
            print('output:',user_stdout)
            if str(user_stdout)==str(tc.output):
                verdict = "Accepted"
            tc.output += '\n' # added extra line to compare user output having extra ling at the end of their output
            if str(user_stdout)==str(tc.output):
                verdict = "Accepted"

        return HttpResponse(verdict)
    return HttpResponse('still building')
def logout_user(request):
    logout(request)
    return redirect('judge:login_page_url')

templates/description.html
<!DOCTYPE html>

<head>
    <title>description page</title>
</head>

<body>
    <form action="{{problem.id}}/verdict" method="POST">
        {%csrf_token%}
        <div>
            {{problem.description}}
        </div>
        <input type="radio" name="language" id = 'python' value = 'python'>
        <label for = 'python' >python</label>
        
        <input type="radio" name="language" id = 'c++' value = 'c++'>
        <label for = 'c++' >c++</label>
        
        <input type="radio" name="language" id = 'c' value = 'c'>
        <label for = 'c' >c</label>
        <br>
        <textarea name = 'code' id="code" rows ='10' cols="40"></textarea>
        <br>
        <input type="submit">
    </form>
</body>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>

    <style>
        /* Reset some default styles */
        body, h1, h2, p, ol, li {
            margin: 0;
            padding: 0;
        }

        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        p {
            margin-bottom: 10px;
        }

        ol {
            list-style-type: none;
            padding: 0;
        }

        li {
            margin-bottom: 8px;
        }

        a {
            text-decoration: none;
            color: #007bff;
        }

        a:hover {
            text-decoration: underline;
            color: #0056b3;
        }
    </style>
</head>

<body>
    <div class="container">
        <p>Logged in as {{ user.username }}</p>
        <ul>
            {% for problem in list %}
                <li><a href="{{ problem.id }}">{{ problem.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <a href="../logout">logout</a>
</body>


</html>

templates/login.html
<!DOCTYPE html>

<head>
    <title>login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #131111;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

        .login-container label {
            display: block;
            margin-bottom: 8px;
        }

        .login-container input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .login-container button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        .login-container button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <form action="" method="POST" class="login-container">
        {% csrf_token %}
        <h >{{message}}</h>
        <div>
            <label for="username">Enter username</label>
            <input name="username" id = 'username' type="text">
        </div>
        <br>
        <div>
            <label for ='password' >Enter password</label>
            <input name="password" id ='password' type="password"> 
        </div>
            <br>
        <input type = 'submit'>
        
    </form>
</body>

templates/signin.html
<!DOCTYPE html>

<head>
    <meta charset="utf-8">
    <title>sigin page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #131111;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 300px;
        }

        .login-container label {
            display: block;
            margin-bottom: 8px;
        }

        .login-container input {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .login-container button {
            background-color: #4caf50;
            color: #fff;
            padding: 10px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }

        .login-container button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <form action="{% url 'judge:add_user_url' %}" method="post" class="login-container">
        {% csrf_token %}
        <div>
            <label for = 'username' >Username</label>
            <input id = 'username' name = 'username' type = 'text'>
        </div>
            <br>
        <div>
        <label for = 'email' >Email id</label>
        <input id = 'email' name = 'email' type="email">
        </div>
        <br>
        <div>
            <label for="'pass1" >Enter password:</label>
            <input id = 'pass1' name = 'pass1' type="password">
        </div>
        <br>
        <div>
            <label for = 'pass2' >Enter password again</label>
            <input id ='pass2' name ='pass2' type="password">
        </div>
        <br>
        <input type="submit">
    </form>
</body>